# org/models.py
from django.db import models

# https://docs.djangoproject.com/en/4.0/topics/db/models/
# NOTE: THIS IS NOT BEING IN USED!
# THIS IS FOR NOW REPLACED WITH AUTH_GROUP!
# class Organization(models.Model):
#     # id is autogenerated
#     name = models.TextField()
