# files/models.py
from django.db import models
from django.contrib.auth.models import Group

class File(models.Model):
    # id is autogenerated
    name= models.CharField(max_length=500)

    # TODO: Better filepath solution, maybe IPFS ;)
    filepath= models.FileField(
        upload_to='uploaded_files/', 
        null=True, 
        verbose_name="")

    uploaded       = models.DateTimeField()
    download_count = models.IntegerField()

    def __str__(self):
        return self.name + ": " + str(self.filepath)
