# org/models.py
from django.db import models

# https://docs.djangoproject.com/en/4.0/topics/db/models/

class Organization(models.Model):
    # id is autogenerated
    name = models.TextField()
