# user/models.py
from django.db import models
from org import Organization

# https://docs.djangoproject.com/en/4.0/topics/db/models/

class User(models.Model):
    # id is autogenerated
    organization = models.ForeignKey(Organization)
    username        = models.CharField(max_length=255)
    password        = models.CharField(max_length=255)
    email           = models.CharField(max_length=255)
    first_name      = models.CharField(max_length=255)
    last_name       = models.CharField(max_length=255)